# Generated by Django 3.0.3 on 2020-10-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_event_manage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='free'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='free', max_length=200),
        ),
    ]
