# Generated by Django 3.0.3 on 2020-10-23 11:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shiftDB', '0003_auto_20200619_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifts',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='shifts',
            name='hospital',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'London - Atkinson Morley Hospital'), (2, 'London - Banstead Hospital'), (3, 'London - Barnes Hospital, London')], default='Blank', max_length=5),
        ),
    ]
